name: ci
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Linting
        run: npm run lint

      - name: Testing
        run: npm run test:ci

      - name: Start
        run: npm run start
